### PR TITLE
Update class-core.php

### PR DESCRIPTION
**Pull request by SomeOneLikeThat**

### CODE REVIEW

**Comment by SomeOneLikeThat** [comment]
Add function not get tag with < 4 char and number

**Comment by holisticnetworking** [comment]
This does not feel like a change this plugin needs to make? How does this enhance the functionality of the plugin? 

Thanks for the contribution!

**Comment by SomeOneLikeThat** [comment]
I think this improve plugin. Get tag is number ( 123, 777, 889)  and some tag with only few char (<4) ( ari, says) is not useless. 
I think if can parser name people in title will helpful

**Comment by khang0001** [comment]
Error with title have ' 
Example title : Sea otters' stone tools provide new clues for archeologists
will have extract tag is otters039

**Comment by holisticnetworking** [comment]
@khang0001 Thank you for the suggestion! The newest release (not yet in the Repo) will address this as an optional setting:
https://github.com/holisticnetworking/title-to-terms/commit/20f68e1734293b7a174e74e276cf405931afc5eb

**Pull request closed without merging**
